### ISSUE TITLE
Date time zone issue.

### ISSUE THREAD

**Issue by joejordanbrown** [benjamincharity/angular-json-calendar#10]
When using the following below in a time zone like GMT

```
// The calendar will begin with today
this.startDate = moment(new Date()).startOf('day').toISOString();
```

`new Date()` would return "Sun Jul 03 2016 13:00:22 GMT+0100 (GMT Summer Time)" for today.

`this.startDate = moment(new Date()).startOf('day').toISOString();` would return "2016-07-02T23:00:00.000Z" which in the above format would be "Sun Jul 02 2016..." which is the day before and I'm  sure July the 2nd is not a Sunday.

Changing `.toISOString();` to `.format()` would fix the problem.

I'm not sure if your still active on this project just thought I'd point this out. 

Any plans for an Angular2 version?

**Comment by benjamincharity** [comment]
@joejordanbrown this is a great catch! Thanks for pointing this out. A big part of why this module came about was to help me get a better handle on dealing with date and time in JavaScript. Lesson from today: I need to test better across various timezones! 

I just pushed out a new release with this fix: https://github.com/benjamincharity/angular-json-calendar/releases/tag/1.0.2

---

I would like to do an Angular 2 version of this module. I'm not exactly sure when this would come about as I haven't done much in Angular 2 yet.  If there are users out there wishing this module existed for Angular 2 I would definitely bump it up on my priorities.
